# Generated by Django 5.0.2 on 2026-02-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_quiztopic_quizresult_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='security_level',
        ),
        migrations.RemoveField(
            model_name='toolusage',
            name='input_data',
        ),
        migrations.RemoveField(
            model_name='toolusage',
            name='result',
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='topic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='toolusage',
            name='tool_name',
            field=models.CharField(max_length=100),
        ),
    ]
