# Generated by Django 5.0.2 on 2026-02-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_quizresult_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='percentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresult',
            name='security_level',
            field=models.CharField(default='BEGINNER', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolusage',
            name='input_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolusage',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toolusage',
            name='tool_name',
            field=models.CharField(max_length=200),
        ),
    ]
